# Generated by Django 5.0.7 on 2024-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('habitat', models.CharField(max_length=20)),
                ('lifestyle', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('group_behavior', models.CharField(max_length=20)),
                ('lifespan', models.IntegerField()),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationToBiomeMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('biome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizID', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('resultID', models.IntegerField(primary_key=True, serialize=False)),
                ('responses', models.JSONField()),
                ('matchedFrog', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
