# Generated by Django 5.0.7 on 2024-08-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationToBiomeMapper',
            new_name='LocationMapper',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='locationmapper',
            old_name='biome',
            new_name='animal_location',
        ),
        migrations.RenameField(
            model_name='locationmapper',
            old_name='location',
            new_name='user_location',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adminID',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quizID',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='matchedFrog',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='resultID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='animal_match',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
