# Generated by Django 5.0.7 on 2024-08-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_answer_question_delete_locationmapper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='group_behavior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lifestyle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
