# Generated by Django 5.0.7 on 2024-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_alter_animal_group_behavior_alter_animal_lifestyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
