# Generated by Django 5.0.7 on 2024-08-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0007_animal_quiz_alter_animal_image_url_alter_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='location',
        ),
        migrations.AddField(
            model_name='animal',
            name='locations',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='matcher.quiz'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group_behavior',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lifestyle',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='animal_match',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
