# Generated by Django 5.0.7 on 2024-08-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0008_remove_animal_location_animal_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='locations',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='matcher.quiz'),
        ),
    ]
