# Generated by Django 5.0.7 on 2024-08-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0011_remove_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
