# Generated by Django 5.0.7 on 2024-09-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0013_alter_animal_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='times_taken',
            field=models.IntegerField(default=0),
        ),
    ]
