# Generated by Django 5.0.7 on 2024-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0014_quiz_times_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
